#include <stdint.h>
#include <stddef.h>

#include "process.h"
#include "thread.h"
#include "vma.h"
#include "vmm.h"
#include "pmm.h"
#include "heap.h"
#include "serial.h"
#include "panic.h"
#include "spinlock.h"
#include "console.h"
#include "signal.h"
#include "vfs.h"
#include "pipe.h"

/* Generated by the build from the sources in user/. Defines struct
 * user_blob, the user_blobs[] table and user_blob_count. */
#include "user_blobs.h"

extern void enter_user_mode(uint32_t eip, uint32_t esp);

static struct process  kernel_process;
static struct process* processes;       /* every process, kernel included */
static uint32_t        next_pid = 1;
static struct spinlock proc_lock;

struct process* process_current(void) {
    struct thread* t = thread_current();
    return t ? t->proc : &kernel_process;
}

static void copy_bytes(uint8_t* dst, const uint8_t* src, uint32_t n) {
    for (uint32_t i = 0; i < n; ++i) dst[i] = src[i];
}

static void copy_str(char* dst, const char* src, uint32_t max) {
    uint32_t i = 0;
    while (src && src[i] && i < max - 1) { dst[i] = src[i]; ++i; }
    dst[i] = '\0';
}

static int str_equal(const char* a, const char* b) {
    while (*a && *a == *b) { ++a; ++b; }
    return *a == *b;
}

static const struct user_blob* find_blob(const char* name) {
    for (uint32_t i = 0; i < user_blob_count; ++i) {
        if (str_equal(name, user_blobs[i].name)) return &user_blobs[i];
    }
    return 0;
}

/* First whitespace-delimited word of a cmdline, NUL-terminated into out. */
static void first_word(const char* cmdline, char* out, uint32_t max) {
    uint32_t i = 0;
    while (cmdline[i] && cmdline[i] != ' ' && i < max - 1) {
        out[i] = cmdline[i];
        ++i;
    }
    out[i] = '\0';
}

/* Program size without loading it: blob length or file size. Negative if
 * the name resolves to nothing. */
static int program_size(const char* prog, uint32_t* size_out) {
    if (prog[0] == '/') {
        struct vfs_stat st;
        if (vfs_stat(prog, &st) != 0 || st.is_dir) return -1;
        *size_out = st.size;
        return 0;
    }

    const struct user_blob* blob = find_blob(prog);
    if (!blob) return -1;
    *size_out = blob->len;
    return 0;
}

/* Copy the program image to USER_CODE_BASE. Runs as the target process, so
 * demand faults land in the right directory whether the source is an
 * embedded blob or a file read through the VFS. */
static int load_image(const char* prog) {
    if (prog[0] == '/') {
        uint32_t off = 0;
        uint8_t* dst = (uint8_t*)USER_CODE_BASE;

        for (;;) {
            uint8_t chunk[512];
            int got = vfs_read(prog, off, chunk, sizeof(chunk));
            if (got < 0) return -1;
            if (got == 0) return 0;

            copy_bytes(dst + off, chunk, (uint32_t)got);
            off += (uint32_t)got;
        }
    }

    const struct user_blob* blob = find_blob(prog);
    if (!blob) return -1;

    copy_bytes((uint8_t*)USER_CODE_BASE, blob->bytes, blob->len);
    return 0;
}

/* Build argc/argv on the user stack from the cmdline and return the esp to
 * enter with. Layout, esp upward: [argc][argv0][argv1]...[0][strings].
 * crt0 reads argc at esp and treats esp+4 as the argv array. */
static uint32_t build_argv(const char* cmdline) {
    char* strings = (char*)(USER_STACK_TOP - CMDLINE_MAX);
    copy_str(strings, cmdline, CMDLINE_MAX);

    /* Tokenize in place, remembering starts. */
    uint32_t argv[16];
    uint32_t argc = 0;
    char* s = strings;

    while (*s && argc < 16) {
        while (*s == ' ') *s++ = '\0';
        if (!*s) break;

        argv[argc++] = (uint32_t)(uintptr_t)s;
        while (*s && *s != ' ') ++s;
    }

    uint32_t* sp = (uint32_t*)((uintptr_t)strings & ~3u);
    *--sp = 0;                                  /* argv terminator */
    for (uint32_t i = argc; i > 0; --i) *--sp = argv[i - 1];
    *--sp = argc;

    return (uint32_t)(uintptr_t)sp;
}

void process_initialize(void) {
    spin_init(&proc_lock, "process");

    /* The kernel is process 0: the boot thread, the kernel address space. */
    kernel_process.pid       = 0;
    kernel_process.state     = PROC_LIVE;
    kernel_process.exit_code = 0;
    kernel_process.parent    = 0;
    kernel_process.thread    = thread_current();
    kernel_process.next      = 0;
    vma_as_init(&kernel_process.as, vmm_kernel_directory());

    processes = &kernel_process;
    thread_current()->proc = &kernel_process;

    kprintf("process: kernel is pid 0\n");
}

static void add_process(struct process* p) {
    uint32_t flags = spin_lock_irq(&proc_lock);
    p->next = processes;
    processes = p;
    spin_unlock_irq(&proc_lock, flags);
}

void process_close_fd(struct process* p, int fd) {
    if (fd < 0 || fd >= FD_MAX) return;

    struct fdesc* d = &p->fds[fd];

    if (d->type == FDT_PIPE_R) pipe_close_reader(d->pipe);
    if (d->type == FDT_PIPE_W) pipe_close_writer(d->pipe);

    d->type = FDT_NONE;
    d->pipe = 0;
}

/* Entry point for a freshly spawned user process. Runs as the new thread,
 * on the new address space, so both the image copy and the argv build
 * demand-fault into the right directory. */
static void user_thread_entry(void* arg) {
    (void)arg;
    struct process* self = process_current();

    char prog[FD_PATH_MAX];
    first_word(self->cmdline, prog, sizeof(prog));

    if (load_image(prog) != 0) {
        kprintf("process %u: couldn't load %s\n", self->pid, prog);
        process_exit(-1);
    }

    uint32_t esp = build_argv(self->cmdline);
    enter_user_mode(USER_CODE_BASE, esp);
}

static const char* short_name(const char* prog) {
    const char* name = prog;
    for (const char* s = prog; *s; ++s) {
        if (*s == '/') name = s + 1;
    }
    return name;
}

int process_spawn(const char* cmdline) {
    char prog[FD_PATH_MAX];
    first_word(cmdline, prog, sizeof(prog));

    uint32_t size;
    if (program_size(prog, &size) != 0) return -1;

    struct process* p = (struct process*)kmalloc(sizeof(struct process));
    if (!p) return -1;

    uint32_t pd = vmm_create_directory();
    if (!pd) { kfree(p); return -1; }

    p->pid       = next_pid++;
    p->state     = PROC_LIVE;
    p->exit_code = 0;
    p->parent    = process_current();
    vma_as_init(&p->as, pd);

    p->sig_pending    = 0;
    p->sig_restorer   = 0;
    p->sig_in_handler = 0;
    for (int i = 0; i < NSIG; ++i) p->sig_handler[i] = SIG_DFL;

    for (int i = 0; i < FD_MAX; ++i) p->fds[i].type = FDT_NONE;
    p->fds[0].type = FDT_CONSOLE;
    p->fds[1].type = FDT_CONSOLE;
    p->fds[2].type = FDT_CONSOLE;

    copy_str(p->cmdline, cmdline, CMDLINE_MAX);

    /* Code region gets write permission too: the loader copies the program
     * in, and these flat binaries keep data in the same pages. W^X is a
     * refinement for when there are real segments. */
    uint32_t code_size = (size + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1);
    if (code_size == 0) code_size = PAGE_SIZE;

    if (!vma_reserve_in(&p->as, USER_CODE_BASE, code_size + PAGE_SIZE,
                        VMA_USER | VMA_WRITE) ||
        !vma_reserve_in(&p->as, USER_STACK_BASE, USER_STACK_SIZE,
                        VMA_USER | VMA_WRITE)) {
        vma_release_all(&p->as);
        vmm_destroy_directory(pd);
        kfree(p);
        return -1;
    }

    /* The thread is schedulable the moment it's listed, and its first act
     * runs on proc's address space - so proc must be set before a tick can
     * pick it. Interrupts off across the gap. */
    uint32_t irq = irq_save();

    struct thread* t = thread_create(short_name(prog), user_thread_entry, 0);
    if (!t) {
        irq_restore(irq);
        vma_release_all(&p->as);
        vmm_destroy_directory(pd);
        kfree(p);
        return -1;
    }

    t->proc       = p;
    t->pinned_cpu = 0;      /* it enters ring 3, and CPU 0 owns the TSS */
    p->thread     = t;

    irq_restore(irq);
    add_process(p);

    return (int)p->pid;
}

int process_fork(struct registers* r) {
    struct process* parent = process_current();

    if (parent == &kernel_process) return -1;

    struct process* child = (struct process*)kmalloc(sizeof(struct process));
    if (!child) return -1;

    uint32_t pd = vmm_create_directory();
    if (!pd) { kfree(child); return -1; }

    child->pid       = next_pid++;
    child->state     = PROC_LIVE;
    child->exit_code = 0;
    child->parent    = parent;
    vma_as_init(&child->as, pd);

    /* Handlers cross the fork, pending signals don't - they were aimed at
     * the parent, not at whoever it becomes. */
    child->sig_pending    = 0;
    child->sig_in_handler = 0;
    child->sig_restorer   = parent->sig_restorer;
    for (int i = 0; i < NSIG; ++i) {
        child->sig_handler[i] = parent->sig_handler[i];
    }

    /* Descriptors cross the fork - and pipe ends are refcounted, so each
     * copied end is another claim on the pipe. */
    for (int i = 0; i < FD_MAX; ++i) {
        child->fds[i] = parent->fds[i];
        if (child->fds[i].type == FDT_PIPE_R) pipe_ref_reader(child->fds[i].pipe);
        if (child->fds[i].type == FDT_PIPE_W) pipe_ref_writer(child->fds[i].pipe);
    }

    copy_str(child->cmdline, parent->cmdline, CMDLINE_MAX);

    if (!vma_clone(&child->as, &parent->as)) {
        vma_release_all(&child->as);
        vmm_destroy_directory(pd);
        kfree(child);
        return -1;
    }

    struct registers frame = *r;
    frame.eax = 0;

    uint32_t irq = irq_save();

    struct thread* t = thread_create_forked(parent->thread->name, &frame);
    if (!t) {
        irq_restore(irq);
        vma_release_all(&child->as);
        vmm_destroy_directory(pd);
        kfree(child);
        return -1;
    }

    t->proc       = child;
    child->thread = t;

    irq_restore(irq);
    add_process(child);

    return (int)child->pid;
}

int process_exec(struct registers* r, const char* path, const char* args) {
    struct process* p = process_current();
    if (p == &kernel_process) return -1;

    uint32_t size;
    if (program_size(path, &size) != 0) return -1;

    /* New cmdline: the program, then whatever args came along. */
    char cmdline[CMDLINE_MAX];
    uint32_t n = 0;
    for (; path[n] && n < CMDLINE_MAX - 1; ++n) cmdline[n] = path[n];
    if (args && args[0] && n < CMDLINE_MAX - 2) {
        cmdline[n++] = ' ';
        for (uint32_t i = 0; args[i] && n < CMDLINE_MAX - 1; ++i) {
            cmdline[n++] = args[i];
        }
    }
    cmdline[n] = '\0';

    /* Tear down the old image. We're on the kernel stack, which is mapped
     * everywhere, so pulling the user mappings out from under ourselves is
     * fine - we're not standing on them. */
    vma_release_all(&p->as);

    uint32_t code_size = (size + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1);

    if (!vma_reserve_in(&p->as, USER_CODE_BASE, code_size + PAGE_SIZE,
                        VMA_USER | VMA_WRITE) ||
        !vma_reserve_in(&p->as, USER_STACK_BASE, USER_STACK_SIZE,
                        VMA_USER | VMA_WRITE)) {
        process_exit(-1);   /* old image is gone; nothing to return to */
    }

    copy_str(p->cmdline, cmdline, CMDLINE_MAX);

    char prog[FD_PATH_MAX];
    first_word(p->cmdline, prog, sizeof(prog));

    if (load_image(prog) != 0) process_exit(-1);

    copy_str(p->thread->name, short_name(prog), THREAD_NAME_MAX);

    /* The new program never installed anyone's handlers. Descriptors stay,
     * Unix style - that's what makes dup2-then-exec pipelines work. */
    p->sig_pending    = 0;
    p->sig_in_handler = 0;
    p->sig_restorer   = 0;
    for (int i = 0; i < NSIG; ++i) p->sig_handler[i] = SIG_DFL;

    r->eip     = USER_CODE_BASE;
    r->useresp = build_argv(p->cmdline);
    r->eax     = 0;

    return 0;
}

int process_wait(uint32_t* pid_out) {
    struct process* self = process_current();

    for (;;) {
        int have_children = 0;

        uint32_t flags = spin_lock_irq(&proc_lock);

        struct process** link = &processes;
        struct process*  zombie = 0;

        for (struct process* p = processes; p; p = p->next) {
            if (p->parent != self) continue;
            have_children = 1;
            if (p->state == PROC_ZOMBIE) { zombie = p; break; }
        }

        if (zombie) {
            while (*link != zombie) link = &(*link)->next;
            *link = zombie->next;

            spin_unlock_irq(&proc_lock, flags);

            int code = zombie->exit_code;
            if (pid_out) *pid_out = zombie->pid;

            thread_reap(zombie->thread);
            kfree(zombie);

            self->sig_pending &= ~(1u << SIGCHLD);
            return code;
        }

        if (!have_children) { spin_unlock_irq(&proc_lock, flags); return -1; }

        if (self->sig_pending & ~(1u << SIGCHLD)) {
            spin_unlock_irq(&proc_lock, flags);
            return -2;
        }

        /* WAITING goes on under the same lock that the scan ran under, and
         * that process_exit takes to wake us.
         *
         * This used to release the lock first. On one CPU the window was
         * theoretical; on four it's the common case - the child exits in
         * that gap, sets us READY, and then we clobber it with WAITING and
         * sleep forever. First real thing SMP broke, and it had been wrong
         * the whole time.
         *
         * Between this unlock and schedule() a wakeup is still possible,
         * but it's harmless: it leaves us READY, and schedule() only
         * downgrades a thread that's still RUNNING. */
        thread_current()->state = THREAD_WAITING;
        spin_unlock_irq(&proc_lock, flags);

        schedule();
    }
}

void process_exit(int code) {
    struct process* self = process_current();

    if (self == &kernel_process) {
        panic("process_exit: the kernel tried to exit");
    }

    /* Closing descriptors is what lets a pipeline finish: the last writer
     * going away is the reader's EOF. */
    for (int i = 0; i < FD_MAX; ++i) process_close_fd(self, i);

    vma_release_all(&self->as);

    __asm__ volatile("mov %0, %%cr3" : : "r"(vmm_kernel_directory()));
    vma_set_active(vma_kernel_space());

    vmm_destroy_directory(self->as.pd);
    self->as.pd = 0;

    self->exit_code = code;
    self->state     = PROC_ZOMBIE;

    console_clear_foreground(self);

    uint32_t flags = spin_lock_irq(&proc_lock);
    for (struct process* p = processes; p; p = p->next) {
        if (p->parent == self) p->parent = &kernel_process;
    }
    if (self->parent && self->parent->thread &&
        self->parent->thread->state == THREAD_WAITING) {
        self->parent->thread->state = THREAD_READY;
    }
    spin_unlock_irq(&proc_lock, flags);

    if (self->parent) signal_send(self->parent, SIGCHLD);

    thread_current()->state = THREAD_DEAD;
    schedule();

    panic("process_exit: scheduled a dead thread");
}

void process_fault_current(uint32_t vector) {
    struct process* self = process_current();

    kprintf("process %u (%s): exception %u in user mode -> SIGSEGV\n",
            self->pid, self->thread->name, vector);

    signal_send(self, SIGSEGV);
}

int process_is_live(uint32_t pid) {
    uint32_t flags = spin_lock_irq(&proc_lock);

    int live = 0;
    for (struct process* p = processes; p; p = p->next) {
        if (p->pid == pid) { live = (p->state == PROC_LIVE); break; }
    }

    spin_unlock_irq(&proc_lock, flags);
    return live;
}

struct process* process_find(uint32_t pid) {
    uint32_t flags = spin_lock_irq(&proc_lock);

    struct process* found = 0;
    for (struct process* p = processes; p; p = p->next) {
        if (p->pid == pid && p->state == PROC_LIVE) { found = p; break; }
    }

    spin_unlock_irq(&proc_lock, flags);
    return found;
}

void process_dump(void) {
    for (struct process* p = processes; p; p = p->next) {
        kprintf("  pid %u %s %s exit=%d\n",
                p->pid,
                p->thread ? p->thread->name : "?",
                p->state == PROC_ZOMBIE ? "zombie" : "live",
                p->exit_code);
    }
}
