#include <stdint.h>
#include <stddef.h>

#include "process.h"
#include "thread.h"
#include "vma.h"
#include "vmm.h"
#include "pmm.h"
#include "heap.h"
#include "serial.h"
#include "panic.h"
#include "spinlock.h"
#include "console.h"

/* Generated by the build from the sources in user/. Defines struct
 * user_blob, the user_blobs[] table and user_blob_count. */
#include "user_blobs.h"

extern void enter_user_mode(uint32_t eip, uint32_t esp);

static struct process  kernel_process;
static struct process* processes;       /* every process, kernel included */
static uint32_t        next_pid = 1;
static struct spinlock proc_lock;

struct process* process_current(void) {
    struct thread* t = thread_current();
    return t ? t->proc : &kernel_process;
}

static void copy_bytes(uint8_t* dst, const uint8_t* src, uint32_t n) {
    for (uint32_t i = 0; i < n; ++i) dst[i] = src[i];
}

static int str_equal(const char* a, const char* b) {
    while (*a && *a == *b) { ++a; ++b; }
    return *a == *b;
}

static const struct user_blob* find_blob(const char* name) {
    for (uint32_t i = 0; i < user_blob_count; ++i) {
        if (str_equal(name, user_blobs[i].name)) return &user_blobs[i];
    }
    return 0;
}

void process_initialize(void) {
    spin_init(&proc_lock, "process");

    /* The kernel is process 0: the boot thread, the kernel address space. */
    kernel_process.pid       = 0;
    kernel_process.state     = PROC_LIVE;
    kernel_process.exit_code = 0;
    kernel_process.parent    = 0;
    kernel_process.thread    = thread_current();
    kernel_process.next      = 0;
    vma_as_init(&kernel_process.as, vmm_kernel_directory());

    /* Kernel VMAs already live in vma.c's kernel space; the process wrapper
     * shares the directory but keeps its own (empty) region list. Faults in
     * kernel context resolve against vma.c's kernel space regardless. */

    processes = &kernel_process;
    thread_current()->proc = &kernel_process;

    kprintf("process: kernel is pid 0\n");
}

static void add_process(struct process* p) {
    uint32_t flags = spin_lock_irq(&proc_lock);
    p->next = processes;
    processes = p;
    spin_unlock_irq(&proc_lock, flags);
}

/* Entry point for a freshly spawned user process. Runs as the new thread,
 * on the new address space (schedule loaded our CR3 before we got here), so
 * the copy below demand-faults pages into the right directory. */
static void user_thread_entry(void* arg) {
    const struct user_blob* blob = (const struct user_blob*)arg;

    copy_bytes((uint8_t*)USER_CODE_BASE, blob->bytes, blob->len);

    enter_user_mode(USER_CODE_BASE, USER_STACK_TOP);
    /* not reached: the only way back into the kernel is a syscall or fault */
}

int process_spawn(const char* name) {
    const struct user_blob* blob = find_blob(name);
    if (!blob) return -1;

    struct process* p = (struct process*)kmalloc(sizeof(struct process));
    if (!p) return -1;

    uint32_t pd = vmm_create_directory();
    if (!pd) { kfree(p); return -1; }

    p->pid       = next_pid++;
    p->state     = PROC_LIVE;
    p->exit_code = 0;
    p->parent    = process_current();
    vma_as_init(&p->as, pd);

    /* Code region gets write permission too: the loader thread has to copy
     * the program in, and the program keeps its data in the same pages.
     * W^X is a refinement for the day there are separate segments. */
    uint32_t code_size = (blob->len + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1);
    if (code_size == 0) code_size = PAGE_SIZE;

    if (!vma_reserve_in(&p->as, USER_CODE_BASE, code_size + PAGE_SIZE,
                        VMA_USER | VMA_WRITE) ||
        !vma_reserve_in(&p->as, USER_STACK_BASE, USER_STACK_SIZE,
                        VMA_USER | VMA_WRITE)) {
        vma_release_all(&p->as);
        vmm_destroy_directory(pd);
        kfree(p);
        return -1;
    }

    /* The thread is runnable the moment it's on the list, and its first act
     * is to fault pages into proc's address space - so proc has to be set
     * before a tick can schedule it. Interrupts off across the gap. */
    uint32_t irq = irq_save();

    struct thread* t = thread_create(blob->name, user_thread_entry,
                                     (void*)blob);
    if (!t) {
        irq_restore(irq);
        vma_release_all(&p->as);
        vmm_destroy_directory(pd);
        kfree(p);
        return -1;
    }

    t->proc   = p;
    p->thread = t;

    irq_restore(irq);
    add_process(p);

    return (int)p->pid;
}

int process_fork(struct registers* r) {
    struct process* parent = process_current();

    /* Kernel threads have no user frame to duplicate. */
    if (parent == &kernel_process) return -1;

    struct process* child = (struct process*)kmalloc(sizeof(struct process));
    if (!child) return -1;

    uint32_t pd = vmm_create_directory();
    if (!pd) { kfree(child); return -1; }

    child->pid       = next_pid++;
    child->state     = PROC_LIVE;
    child->exit_code = 0;
    child->parent    = parent;
    vma_as_init(&child->as, pd);

    if (!vma_clone(&child->as, &parent->as)) {
        vma_release_all(&child->as);
        vmm_destroy_directory(pd);
        kfree(child);
        return -1;
    }

    /* The child resumes exactly where the parent is - same registers, same
     * user stack, same eip - except eax, which is how the two sides of the
     * fork learn who they are. */
    struct registers frame = *r;
    frame.eax = 0;

    /* Same race as spawn: the child is schedulable before proc is set
     * unless interrupts are held off across the assignment. */
    uint32_t irq = irq_save();

    struct thread* t = thread_create_forked(parent->thread->name, &frame);
    if (!t) {
        irq_restore(irq);
        vma_release_all(&child->as);
        vmm_destroy_directory(pd);
        kfree(child);
        return -1;
    }

    t->proc       = child;
    child->thread = t;

    irq_restore(irq);
    add_process(child);

    return (int)child->pid;
}

int process_exec(struct registers* r, const char* name) {
    struct process* p = process_current();
    if (p == &kernel_process) return -1;

    const struct user_blob* blob = find_blob(name);
    if (!blob) return -1;

    /* Tear down the old image. We're on the kernel stack (heap, shared into
     * every directory), so pulling the user mappings out from under
     * ourselves is fine - we're not standing on them. */
    vma_release_all(&p->as);

    uint32_t code_size = (blob->len + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1);

    if (!vma_reserve_in(&p->as, USER_CODE_BASE, code_size + PAGE_SIZE,
                        VMA_USER | VMA_WRITE) ||
        !vma_reserve_in(&p->as, USER_STACK_BASE, USER_STACK_SIZE,
                        VMA_USER | VMA_WRITE)) {
        /* Old image is gone and the new one won't fit: nothing to return
         * to. Exit rather than resume a program that no longer exists. */
        process_exit(-1);
    }

    copy_bytes((uint8_t*)USER_CODE_BASE, blob->bytes, blob->len);

    /* Rewriting the saved frame is what makes the iret land in the new
     * program instead of after the old one's int 0x80. */
    r->eip     = USER_CODE_BASE;
    r->useresp = USER_STACK_TOP;
    r->eax     = 0;

    return 0;
}

int process_wait(uint32_t* pid_out) {
    struct process* self = process_current();

    for (;;) {
        /* Any zombie child? */
        int have_children = 0;

        uint32_t flags = spin_lock_irq(&proc_lock);

        struct process** link = &processes;
        struct process*  zombie = 0;

        for (struct process* p = processes; p; p = p->next) {
            if (p->parent != self) continue;
            have_children = 1;
            if (p->state == PROC_ZOMBIE) { zombie = p; break; }
        }

        if (zombie) {
            while (*link != zombie) link = &(*link)->next;
            *link = zombie->next;
        }

        spin_unlock_irq(&proc_lock, flags);

        if (zombie) {
            int code = zombie->exit_code;
            if (pid_out) *pid_out = zombie->pid;

            /* Everything else went at exit time; what's left is what the
             * zombie couldn't free while running on it. */
            thread_reap(zombie->thread);
            kfree(zombie);

            return code;
        }

        if (!have_children) return -1;

        /* Block until an exit wakes us. WAITING, not SLEEPING - the timer
         * has no business waking this thread. */
        thread_current()->state = THREAD_WAITING;
        schedule();
    }
}

void process_exit(int code) {
    struct process* self = process_current();

    if (self == &kernel_process) {
        panic("process_exit: the kernel tried to exit");
    }

    /* Free the user side now, while there's still a thread to do it. The
     * directory can't be destroyed while CR3 points at it, so switch to the
     * kernel directory first - our stack is in the heap, which is mapped
     * everywhere, so the ground doesn't move under us. */
    vma_release_all(&self->as);

    __asm__ volatile("mov %0, %%cr3" : : "r"(vmm_kernel_directory()));
    vma_set_active(vma_kernel_space());

    vmm_destroy_directory(self->as.pd);
    self->as.pd = 0;

    self->exit_code = code;
    self->state     = PROC_ZOMBIE;

    /* Orphans go to the kernel process, which reaps strays in its wait. */
    uint32_t flags = spin_lock_irq(&proc_lock);
    for (struct process* p = processes; p; p = p->next) {
        if (p->parent == self) p->parent = &kernel_process;
    }
    if (self->parent && self->parent->thread &&
        self->parent->thread->state == THREAD_WAITING) {
        self->parent->thread->state = THREAD_READY;
    }
    spin_unlock_irq(&proc_lock, flags);

    thread_current()->state = THREAD_DEAD;
    schedule();

    panic("process_exit: scheduled a dead thread");
}

void process_kill_current(uint32_t vector) {
    struct process* self = process_current();

    kprintf("process %u (%s) killed: exception %u in user mode\n",
            self->pid, self->thread->name, vector);

    process_exit(128 + (int)vector);
}

int process_is_live(uint32_t pid) {
    uint32_t flags = spin_lock_irq(&proc_lock);

    int live = 0;
    for (struct process* p = processes; p; p = p->next) {
        if (p->pid == pid) { live = (p->state == PROC_LIVE); break; }
    }

    spin_unlock_irq(&proc_lock, flags);
    return live;
}

void process_dump(void) {
    for (struct process* p = processes; p; p = p->next) {
        kprintf("  pid %u %s %s exit=%d\n",
                p->pid,
                p->thread ? p->thread->name : "?",
                p->state == PROC_ZOMBIE ? "zombie" : "live",
                p->exit_code);
    }
}
